"use client";

import { db } from "@/utils/db";
import React, { useEffect, useState } from "react";
import { AIoutput } from "@/utils/schema"; // Adjust the import path based on your project structure
import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import Templates from "@/app/(data)/Templates";
import Image from "next/image";
import { useUser } from "@clerk/clerk-react";
import { sql } from "drizzle-orm";

interface AIoutputData {
  id: number;
  formData: string;
  aiResponse: string;
  templateSlug: string;
  createdBy: string;
  createdAt: string;
}

const History = () => {
  const [historyData, setHistoryData] = useState<any[]>([]);
  const { user } = useUser();

  useEffect(() => {
    const fetchData = async () => {
        if (!user?.primaryEmailAddress?.emailAddress) {
            console.error("User not authenticated");
            return;
          }
      try {
        const data = await db
          .select()
          .from(AIoutput)
          .where(sql`${AIoutput.createdBy} = ${user.primaryEmailAddress.emailAddress}`);

        setHistoryData(data);
      } catch (error) {
        console.error("Error fetching history data:", error);
      }
    };

    fetchData();
  }, [user]);

  return (
    <div className="bg-white p-3 m-5 rounded-md border">
      <div>
        <h2 className="text-3xl font-bold">History</h2>
        <p>History of all the content generated by the user</p>
      </div>

      <div className="mt-5">
        {historyData.length > 0 ? (
          <Table>
            <TableCaption>A list of the generated content.</TableCaption>
            <TableHeader>
              <TableRow>
                <TableHead>Template</TableHead>
                <TableHead>AI Response</TableHead>

                <TableHead>Created At</TableHead>
                <TableHead>Words</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {historyData.map((item, index) => (
                <TableRow key={index}>
                  <TableCell className="w-[150px]">
                    {
                      <div className="flex gap-2">
                        <Image
                          src={
                            Templates.find(
                              (template) => template.slug === item.templateSlug
                            )?.icon ?? ""
                          }
                          alt="icon"
                          width={20}
                          height={20}
                        />
                        {
                          Templates.find(
                            (template) => template.slug === item.templateSlug
                          )?.name
                        }
                      </div>
                    }
                  </TableCell>
                  <TableCell className="line-clamp-3">
                    {item.aiResponse}
                  </TableCell>

                  <TableCell>{item.createdAt}</TableCell>
                  <TableCell>{item.aiResponse.split(" ").length}</TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        ) : (
          <p>No history data found.</p>
        )}
      </div>
    </div>
  );
};

export default History;
